application: ejcartercom-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.*\.(gif|png|jpg|css|js|ico|xml|html))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|css|js|ico|xml|html))

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
